# Applies direction A (the "therefore" mark) to the app, landing page and favicon.
import re, json, shutil, pathlib
R = pathlib.Path(__file__).resolve().parents[2]
s = (R/'brand/ergo2/A-lockup.svg').read_text()
vb = re.search(r'viewBox="([^"]+)"', s).group(1)
mt = re.search(r'<g transform="([^"]+)"><circle', s).group(1)
circles = re.findall(r'<circle cx="([\d.]+)" cy="([\d.]+)" r="([\d.]+)"', s)
wt = re.search(r'</g><g transform="([^"]+)"><path', s).group(1)
paths = re.findall(r'<path d="([^"]+)"', s)
word = ' '.join(paths)
dots = [[float(a), float(b), float(c)] for a, b, c in circles]
data = {"vb": vb, "mark": mt, "dots": dots, "word": word, "wordT": wt}
(R/'src/components/brand.js').write_text('// Ergo logo, direction A: the "therefore" mark (quote, job, paid) + wordmark. Generated by brand/work/apply_a.py.\nexport const LOGO = ' + json.dumps(data) + ';\n')
c = ''.join(f'<circle cx="{x}" cy="{y}" r="{r}" fill="{"var(--chalk)" if i == 2 else "currentColor"}"/>' for i, (x, y, r) in enumerate(dots))
svg = f'<svg class="logotype" viewBox="{vb}" aria-hidden="true"><g transform="{mt}">{c}</g><path d="{word}" fill="currentColor" transform="{wt}"/></svg>'
b = R/'landing/body.html'
t = b.read_text()
t2 = re.sub(r'<svg class="logotype".*?</svg>', lambda m: svg, t, count=1, flags=re.S)
assert t2 != t
t2 = t2.replace('brand/ergo/png/ergo-app-icon-180.png', 'brand/ergo2/png/A-icon-180.png')
b.write_text(t2)
for f in ('app.html', 'demo.html'):
    p = R/f; p.write_text(p.read_text().replace('brand/ergo/png/ergo-app-icon-180.png', 'brand/ergo2/png/A-icon-180.png'))
shutil.copy(R/'brand/ergo2/A-icon.svg', R/'favicon.svg')
print('ok', len(dots), len(paths))
